import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { signIn, signOut, useSession, } from 'next-auth/client';

export default function Home() {
  const [session] = useSession();
  console.log(session)
  
  
  async function handleClick(e){
    if(session){
      var userDetailsJSON={};
      userDetailsJSON.email = session.user.email;
      userDetailsJSON.name = session.user.name;
      userDetailsJSON.photo = session.user.image;

      console.log("body print"+JSON.stringify(userDetailsJSON));

      const response = await fetch('https://green-lab-f5a9.viswacloudflare.workers.dev/', {
        method: 'POST',
        headers: {
          
            'Content-Type' : 'application/json'
        },
        body: JSON.stringify(userDetailsJSON)
    });
    }
  }
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Image src="/dummy_logo.png" alt="Vercel Logo" width={800} height={400} />
        <h1 className={styles.title}>
          Conference Name
        </h1>
        <p>Celberate the conference without fail.October 31, 2021 9am-1pm PT / Online.</p>

        {!session && <>
  Not signed in <br/>
  <button onClick={() => signIn()} className={styles.ticketbutton}>Claim Your Digital Ticket</button>
</>}
{session && <>
  
  <button onClick={handleClick}  className={styles.ticketbutton}>Check your Ticket</button>
</>}

       </main>

       <div  className={styles.about}>
         <div className={styles.aboutleft}>
           <h5>ABOUT THE EVENT</h5>
           <p>Two lines about the event. This is the first time we going to meet int he onlin. and this will be fully free event
             with the help from the community, run by the community.
           </p>
           <div></div>
         </div>
         <div className={styles.aboutright}>
           
         </div>
       </div>

       <div  className={styles.speaker}>
        <h3>Want to become Speaker</h3>
        <h5>CFP is Still Open</h5>
        <p><a href="#">Click to submit propsal</a></p>
        </div>

        <div  className={styles.sponser}>
        <h3>Sponser</h3>
        <h5>WANT TO BECOME A SPONSOR?</h5>
        <p><a href="#">Click to Sponser</a></p>
        </div>
      
      <footer >
        <section  className={styles.footersection}>
          <a href="https://twitter.com" target="_blank"rel="noopener noreferrer">
            <Image src="/twitter.png" alt="Twitter Logo" width={64} height={64} />
          </a>
          <a href="https://facebook.com" target="_blank"rel="noopener noreferrer">
          <Image src="/facebook.png" alt="Facebook Logo" width={64} height={64} />
          </a>
          <a href="https://linkedin.com" target="_blank"rel="noopener noreferrer">
          <Image src="/linkedin.png" alt="Facebook Logo" width={64} height={64} />
          </a>
          </section>
        <section className={styles.footer}>
          
        <a>
          Made with Love by Community
        </a>
        </section>
      </footer>
    </div>
  )

}
